### ISSUE TITLE
Admin issue

### ISSUE THREAD

**Issue by cyberbudy** [fabiocaccamo/django-treenode#1]
There a few errors in the changelist_view

`AttributeError: 'TestTreeNode' object has no attribute 'tn_parents_pks'`

And

`AttributeError: 'TestTreeNode' object has no attribute 'tn_parents_count'`

I suppose `ancestors` should be used instead of `parents`

**Comment by fabiocaccamo** [comment]
Thanks for the report, fixed in `0.6.1` version.
Any other feedback would be very appreciated!

**Comment by cyberbudy** [comment]
`get_parents_count` - this method is specified only in the readme. Same as other `parents` things.

**Comment by fabiocaccamo** [comment]
Renamed parents to ancestors everywhere, sorry.
