### ISSUE TITLE
Implement treenode in CreateView or ModelForm

### ISSUE THREAD

**Issue by diek** [fabiocaccamo/django-treenode#10]
I am trying implement treenode without admin, and I was curious to know if you have an example of either a CreateView or a ModelForm. Or have any suggestions. I really like your efforts, amazing job, but I do not want regular users into the admin.

**Comment by fabiocaccamo** [comment]
If you don’t want the admin just extend the model abstract class.

**Comment by diek** [comment]
I do want the admin, it works perfect. I just also need a user form for non-admins, I am just having a hard time getting my head wrapped around making a form that has fields not in my model, the tn_parent would be the primary example of that. And I was curious to know if you have an example of either a CreateView or a ModelForm using treenode.

**Comment by diek** [comment]
Got it, if you want I will upload a class based view example

**Comment by fabiocaccamo** [comment]
Ah ok, sorry... I didn't understood your need yesterday.
Sure, feel free to send it, any contribution is appreciated.

**Comment by diek** [comment]
will do
