### ISSUE TITLE
django-fast-treenode

### ISSUE THREAD

**Issue by iacobfred** [fabiocaccamo/django-treenode#130]
@fabiocaccamo , have you seen [django-fast-treenode](https://github.com/TimurKady/django-fast-treenode) ?

I [suggested](https://github.com/TimurKady/django-fast-treenode/issues/4) that perhaps the changes in django-fast-treenode should be contributed to this package rather than maintained separately. What do you think? 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/django-treenode/issues/130">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-treenode/issues/130/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-treenode/issues/130/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@iacobfred I totally agree. @TimurKady sent me the improved version long time ago, but I had not the time to check and compare it, because he sent me a whole refactored package instead of a PR with incremental changes.

So... if you want/have the time to work on a PR I will be glad to review and eventually merge it.

**Comment by TimurKady** [comment]
Hey folks, I'll genuinely be happy to wrap up my project! From the beginning, I suggested not creating separate entities and instead combining improvements. Furthermore, I'm more than willing to just jump in and assist.

Fabio, on my end, I've done everything within my capacity. As they say, the ball is in your court!

**Comment by iacobfred** [comment]
Hi @TimurKady , it's good to hear you're willing to jump in and wrap up your project.

As @fabiocaccamo pointed out, what we have currently is a whole refactored project (django-fast-treenode) rather than a PR. To wrap this up, we need to open a PR instead of sending @fabiocaccamo a whole refactored package. If there is no PR, then we haven't yet done everything within our capacity and the ball is not yet in Fabio's court.

I think the steps to wrap this up are as follows:
1. Make a new fork of django-treenode
2. Make incremental changes (based on the changes you've already made in django-fast-treenode)
3. Open a PR; get those changes merged into django-treenode
4. Repeat 2–3 until django-treenode has all of your improvements from django-fast-treenode
5. Archive django-fast-treenode

**Comment by fabiocaccamo** [comment]
@iacobfred @TimurKady I close this issue since I don't think that anyone is working on a PR.

**Comment by TimurKady** [comment]
Fabio, sorry, I'm currently busy with a large complex project. I can't maintain a PR. 
You are free to use my code. Once you transfer it, I'll just delete my repo
