### ISSUE TITLE
How to Keep Accordion Nesting When Sorting by Other Fields

### ISSUE THREAD

**Issue by brianjbuck** [fabiocaccamo/django-treenode#16]
When using Accordion nesting as the display mode In the Django admin, if you sort by a different field, the display mode switches to Breadcrumb.

How do I override the admin to maintain the Accordion display mode?

**Comment by fabiocaccamo** [comment]
@brianjbuck the current behavior is intentional, it happens also when a search filter is present. Using the django's admin columns ordering all rows are sorted using the selected field including all descendants.
Any idea to overcome this problem will be appreciated.

**Comment by fabiocaccamo** [comment]
@brianjbuck I close this issue since it is not my intention to work on it. If you want to do it feel free to submit a PR.
