### ISSUE TITLE
At the 6th level, treenode reverses the order of descendants.

### ISSUE THREAD

**Issue by kynamd** [fabiocaccamo/django-treenode#17]
**Python version**
3.8.0

**Django version**
2.2.7

**Package version**
django-treenode: 0.14.0

**Current behavior (bug description)**
Here is a single branch with 5 nodes:
![image](https://user-images.githubusercontent.com/26850832/73409860-143a9c80-4333-11ea-8642-0e48d1eb6197.png)

When I add the 6th descendant node to the branch, the order of descendants begins to reverse as seen below:
![image](https://user-images.githubusercontent.com/26850832/73409914-3b916980-4333-11ea-94c0-21dbb73a7e2b.png)

When I add the 7th and 8th descendant, it follows the same reverse behavior:
![image](https://user-images.githubusercontent.com/26850832/73409937-519f2a00-4333-11ea-87ca-a828b74f0073.png)

Here's a snapshot of the table:
![image](https://user-images.githubusercontent.com/26850832/73409963-6085dc80-4333-11ea-807e-190adee64ea1.png)

Am I doing something wrong?

**Expected behavior**
?

Thank you!

**Comment by fabiocaccamo** [comment]
@kynamd wow, thank you for reporting this unexpected behavior. I will debug and fix it as soon as possible.

**Comment by fabiocaccamo** [comment]
@kynamd fixed in `0.14.1` version (tested against 120 levels of depth).
You just need to update your tree (you can do it by saving any model in the admin).
