### ISSUE TITLE
Display parents structure in select input

### ISSUE THREAD

**Issue by joaquinperaza** [fabiocaccamo/django-treenode#18]
Display parents structure in select input in form when creating object with FK reference to tn Model

**Comment by fabiocaccamo** [comment]
@joaquinperaza yes, you are right, otherwise it's hard to understand the node path.

**Comment by joaquinperaza** [comment]
My quick solution was modifying the _unicode_ method in the model:

`		def _unicode_(self):
			ancestros=""   
			for ancestro in self.ancestors:
				ancestros+=ancestro.nombre+"/"            
			return ancestros+self.nombre`

**Comment by fabiocaccamo** [comment]
@joaquinperaza the problem is that this change affects many other situations, it needs to be tested well before being changed.

**Comment by joaquinperaza** [comment]
Sure, It's just a workaround, for the moment it's seems to work but I will update if it cause any problems ![image](https://user-images.githubusercontent.com/18288382/78693194-49cea980-78d1-11ea-9555-42770da9c1cb.png)

![image](https://user-images.githubusercontent.com/18288382/78693309-74206700-78d1-11ea-97d5-89fb583fc8ac.png)

**Comment by fabiocaccamo** [comment]
Try to change `treenode_display_mode` property in the admin, I think that you could see some uncorrect behavior.

**Comment by fabiocaccamo** [comment]
@joaquinperaza any feedback?

**Comment by fabiocaccamo** [comment]
@joaquinperaza just override the `__str__` method in your model:
```python
def __str__(self):
    d = [obj.get_display(indent=False) for obj in self.get_breadcrumbs()]
    return ' / '.join(d)
```
