### ISSUE TITLE
Ordering Problem with recursive method

### ISSUE THREAD

**Issue by aarondiazr** [fabiocaccamo/django-treenode#19]
Hi!

I've a problem when execute TreeNode Model with nested list, the Tree isn´t respect the order iteration, for example:

```python
FAKE_PAYLOAD = [
    { 'name': "LEGAL",
      'children': [{ 'name': "CORPORATIVO",
                     'children': [{ 'name': "Sub-SubFolder 1" },
                                  { 'name': "Sub-SubFolder 2" },
                                  { 'name': "Sub-SubFolder 3" },
                                  { 'name': "Sub-SubFolder 4" },
                                  { 'name': "Sub-SubFolder 5" },
                                  { 'name': "Sub-SubFolder 6" },
                                  { 'name': "Sub-SubFolder 7" },
                                  { 'name': "Sub-SubFolder 8" },
                                  { 'name': "Sub-SubFolder 9" },
                                  { 'name': "Sub-SubFolder 10" },
                                  { 'name': "Sub-SubFolder 11" },
                                  { 'name': "Sub-SubFolder 12" },
                                  { 'name': "Sub-SubFolder 13" },
                                  { 'name': "Sub-SubFolder 14" },
                                  { 'name': "Sub-SubFolder 15" },
                                  ] },
                   { 'name': "CONTRACTUAL",
                     'children': [
                         { 'name': "Sub-SubFolder 1" },
                         { 'name': "Sub-SubFolder 2" }] },
                   { 'name': "GOBIERNO",
                     'children': [{ 'name': "Sub-SubFolder 1" }] }
                   ] },
]
```

My model is like this:
```python
class FakeFolder(TreeNodeModel):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.name
```

My recursive method is:
```python
def write_tree(tree_list, parent = None):
    for folder in tree_list:
        folder_obj = FakeFolder.objects.create(name=folder['name'])
        if parent:
            folder_obj.set_parent(parent)
        if 'children' in folder:
            write_tree(folder['children'], folder_obj)
```

After, executed **get_children()** of root node, the list it seems wrong order:

```shell
FakeFolder.objects.all()[0].children
[<FakeFolder: CONTRACTUAL>, <FakeFolder: CORPORATIVO>, <FakeFolder: GOBIERNO>]
```
And the order of children_pks is **'106,90,109'**, when the correct order must be maybe **'90,106,109'** or:
```shell
[<FakeFolder: CORPORATIVO>, <FakeFolder: CONTRACTUAL>, <FakeFolder: GOBIERNO>]
```

With this package it's possible to set order manually? I don't see a method for this. The only way that I've found is with the priority property but only works in descendent order

Thanks!

**Comment by fabiocaccamo** [comment]
@aarondiazr by default the objects are ordered alphabetically by their __str__ representation. 

In the `Meta` class you must extend the `TreeNodeModel.Meta`:
```python
class Meta(TreeNodeModel.Meta):
        verbose_name = _('Fake Folder')
        verbose_name_plural = _('Fake Folders')
```

If you need a different order you must use the `tn_priority` field, that works in descending order and will be used internally to compute the hidden `tn_order` field value (don't edit this field manually). 

The reason behind the descending order is **make possible to add new objects before the existing ones** using a `PositiveSmallIntegerField`. With an ascending ordering this would be not possible if there are already records with the ordering set to `0`.

I hope to have been helpful, for any doubt, feature request or bug just let me know.

**Comment by aarondiazr** [comment]
Thanks buddy, amm maybe if there are possible to order tree in based of custom property like a integer in ascending or descending order instead of alphabetically will be great. Because in the practice will need modify the order based on specific use case. Now I will override the get_children method to make possible different order...

I see behind of magic performance one weakness, for example if execute this on microservice or serveless, will always go to database because the memory location of cache is independently of any instance of docker, maybe a feature with redis will be great.

**Comment by fabiocaccamo** [comment]
You can already customize the ordering using `tn_priority` field, if you are using the admin just add `tn_priority` to `list_display` and `list_display_editable`.

Interesting weakness, I never used it in a scenario like yours. Feel free to open an issue about this since it could be of interest to many others.

This can be achieved easily just modifying the [cache](https://github.com/fabiocaccamo/django-treenode/blob/master/treenode/cache.py) module.

**Comment by aarondiazr** [comment]
Could you give and example to customize a order with `tn_priority` using cache, but without use admin? Because I´ve seen `tn_priority` is accoupled to `__get_node_order_str`.

The only way I've found is:
```python
    def get_children_queryset(self):
        return super(Folder, self).get_children_queryset(cache=False).order_by('tn_priority')
```

But this approach avoid cache, because you get a cached tree based in order of `tn_children_pks`, `tn_ancestors_pks`, `tn_siblings_pks `and `tn_descendants_pks` strings with the filter `pk__in`, right?

**Comment by fabiocaccamo** [comment]
@aarondiazr just customize the `tn_priority` field value, then execute `cls.update_tree()`.
