### ISSUE TITLE
Strange "AttributeError: can't set attribute" while using "index" as field name

### ISSUE THREAD

**Issue by paviano** [fabiocaccamo/django-treenode#25]
Hi!
I noted that django-admin creation page throw an "AttributeError" while using "index" as field name.

I'm using Python 3.8.5 and Django 3.0.8

don't know if that can be considered a problem.

Really nice package anyway 😁😁

**Comment by fabiocaccamo** [comment]
Hi @paviano, thank you for reporting this.

Could you describe better the problem and the steps to follow to reproduce it please?

**Comment by paviano** [comment]
Ciao allora:

-aggiungere un campo "int" di nome "index" a un modello

-implementazione standard per l'admin page

"@admin.register(Impostazione)
class ImpostazioneAdmin(TreeNodeModelAdmin, ImportExportModelAdmin):
    treenode_display_mode = TreeNodeModelAdmin.TREENODE_DISPLAY_MODE_ACCORDION
    form = TreeNodeForm"
    

Ecco uno screenshot della traccia
    
    
    
![immagine](https://user-images.githubusercontent.com/59799846/103342604-38928200-4a8a-11eb-9430-23307baeff48.png)

**Comment by fabiocaccamo** [comment]
As you can see in the documentation, in the `TreenodeModel` there is already a getter property named `index`, so your field name clashes with the existing property, you should name it with another name.

**Comment by paviano** [comment]
Yep, 

but note that:

"The TreeNodeModel abstract class adds many fields (**prefixed with tn_ to prevent direct access**) and public methods to your models."

So its in conflict with the verbose name? 😊

**Comment by fabiocaccamo** [comment]
You are right, initially property getters were located in an optional model mixin, but after I merged the mixin in the main model.
Maybe it would be useful to add a setting to avoid the use of property getters.
