### ISSUE TITLE
Note in docs about thread/multi process safety

### ISSUE THREAD

**Issue by stuaxo** [fabiocaccamo/django-treenode#26]
The worst problem I've had with treebeard is lack of thread/multi process safety.

It's easily demonstrated by running two processes at the same time that each have a loop that adds nodes to the tree.
(because the key generation + adding nodes is not an atomic operation).

Does django-treenode solve this ?

If it does it would be great to have a note in the README.

**Comment by fabiocaccamo** [comment]
@stuaxo check here: the tree data is computed and then [the nodes are updated all at once](https://github.com/fabiocaccamo/django-treenode/blob/master/treenode/models.py#L354).

Frankly I have not tested it in that scenario and there are not specific tests, so if you can test it directly and maybe also add some tests it would be great and I would add a note to the README.

**Comment by stuaxo** [comment]
I'm a bit bogged down at the moment, but this is something I check up on semi-regularly so bound to end up back on this ticket in future, so will put some notes here.

Having a brief look at that, it's definitely better due to its atomic nature - though I wonder if items with the node id could clash.

In the case where I hit the error in treebeard, the tree represented a tree of web pages and we were creating new ones during unittesting.

This meant, if two "sub pages" were created of a node at the same time, we would hit the error ... this is because the node ids used were predictable and would clash ... however from our user POV we didn't care what those keys were.

So, either a lock was needed, or a change to node ids, so that they wouldn't clash, or something else.

**Comment by fabiocaccamo** [comment]
@stuaxo I'm confident it will work fine, when you will have time to test it better please come back to update this issue before it will become stale.

**Comment by stuaxo** [comment]
I'll close it for now, as it could be a while - I'll still find this since it could be > year :)

**Comment by fabiocaccamo** [comment]
Ok, don't worry, come back soon :)

**Comment by onekiloparsec** [comment]
I'd be interested in the tests / comparison, because I have the same worries. Actually, I may be doing it myself if I find the time (business as usual). So far I've been adding this (and other similar) to my node model to fight against multi-thread problems:

```
@classmethod
    def lock_then_add_sibling(cls, id, validated_data):
        with transaction.atomic():
            node = (cls.objects.select_for_update().get(id=id))
            child_node = node.add_sibling(**validated_data)
        return child_node
```

**Comment by fabiocaccamo** [comment]
@onekiloparsec could you send a PR with a test that should pass?

**Comment by onekiloparsec** [comment]
Hm... I'd be happy to do so, but it requires a bit of thinking. One needs a DB, preferably in memory, and automate migrations in setUp test class, isn't it? 

A bit late right now for my brain, but I can try tomorrow.

**Comment by stuaxo** [comment]
The database is already setup during testing.  But getting things working in a sane way with multi-process to trigger this could be tricky.

I guess you could do something with subprocess, and pass them the details to connect to the test database, then wait for them to complete.

sqlite in memory appears to be the default.   If you want to test under PostGres then doing so under CI, probably makes sense - i.e. github actions.

**Comment by fabiocaccamo** [comment]
If you run tests locally using tox, both sqlite and postgress databases are used.

I think that `subprocess` is the right way to test this.

**Comment by fabiocaccamo** [comment]
> The worst problem I've had with treebeard is lack of thread/multi process safety.
> 
> 
> 
> It's easily demonstrated by running two processes at the same time that each have a loop that adds nodes to the tree.
> 
> (because the key generation + adding nodes is not an atomic operation).
> 
> 
> 
> Does django-treenode solve this ?
> 
> 
> 
> If it does it would be great to have a note in the README.

Could you explain better your scenario to replicate it in a test case?

**Comment by fabiocaccamo** [comment]
@stuaxo @onekiloparsec I close this issue due to inactivity, I will be glad to re-open it if you provide some useful feedback and/or test.

**Comment by stuaxo** [comment]
Apologies for not getting back to you, I work on contracts - so different places every 9 - 12 months, so I no longer have access to the project I was working on there.

The issue we had, was that I we were writing code that update Django CMS using their API, which in turn uses TreeBeard underneath.

As we were using celery, at first this ran with more than one process, this broke things until I forced only one to run at once.

Since we weren't directly using TreeBeard it was tricky for me to come up with a scenario.

We had two processes creating pages - the pages in DjangoCMS uses TreeBeard to maintain a hierachy of pages, so I guess each was trying to create a child node (child page of the root page) at "the same time".

Note, the updates took long enough (not due to treebeard, but the combination of django cms and the project I was working on), that "the same time" was in the range of a second or so.

It was easy to reproduce there, we just needed something creating / editing a lot of pages at once.
