### ISSUE TITLE
Multiple values for display field

### ISSUE THREAD

**Issue by zszep** [fabiocaccamo/django-treenode#27]
Could it be possible to make "treenode_display_field" take multiple field, e.g. 'postal_code, town'

**Comment by fabiocaccamo** [comment]
@zszep this is a good idea, unfortunately this is not supported, but it should be very easy to implement it.
I think the best thing would be to support a `callable`, it should be implemented [here](https://github.com/fabiocaccamo/django-treenode/blob/master/treenode/models.py#L192).

**Comment by fabiocaccamo** [comment]
@zszep btw you can override the model `get_display` method.

**Comment by zszep** [comment]
Following your advice and adding this code to models.py works great:

    def get_display(self, indent=True, mark='— '):
        indentation = (mark * self.tn_ancestors_count) if indent else ''
        indentation = force_text(indentation)
        field_name = getattr(self, 'treenode_display_field', 'pk')
        text = self.postal_code + ' ' + self.town
        return indentation + text

**Comment by fabiocaccamo** [comment]
Let's keep this issue open, I want to add a `get_display_text` method that returns just the text without the indentation. 
In this way in case of override there will be no need to copy/paste the indentation part.

**Comment by fabiocaccamo** [comment]
@zszep you can upgrade to `0.16.0` version and just override the `get_display_text` method.
