### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by TimurKhan** [fabiocaccamo/django-treenode#28]
Thank you so much! You have done a great job and created a very good product. At the same time, it should be noted that its main drawback is scarce documentation. It would be nice if you could take a little time and add some small comments to the code.
It's just that I, for example, spend a lot of time to understand what this or that parameter does. For example, I still did not understand what is node priority?
Tnx!

**Comment by fabiocaccamo** [comment]
@TimurKhan thank you very much, I'm glad that you like it!
I know that the documentation could be improved a lot. I would like to do that, but for me it is a low-priority task and when I have some time to spend on open-source I prefer to fix bugs or implement new features.
Maybe one day I will have some sponsors I will add a great documentation to all my packages.

**Comment by fabiocaccamo** [comment]
**The priority can be used to customize nodes ordering using the admin.**

To keep nodes sorted correctly with respect to their parents but in a flat data-structure, nodes are sorted **alphabetically** using a str that is generated [here](https://github.com/fabiocaccamo/django-treenode/blob/master/treenode/models.py#L377).

#2 is one of the features I would like to work on.

**Comment by TimurKhan** [comment]
Tnx!!!
