### ISSUE TITLE
Cache update error

### ISSUE THREAD

**Issue by TimurKhan** [fabiocaccamo/django-treenode#29]
**Python version** 3.9
**Django version** 3.2
**Package version** 0.16.0

**Current behavior (bug description)**
I just want to say that the error manifests itself in very exotic circumstances.
1. I created an abstract model from TreeNodeModel
2. Dynamically, using the operator `type()`, I create an instance of the tree model, inheriting the model from the previously created abstract model. Entries in `ContentType` and `Permissions `have been created. The model is registered in the apps register.
3. Dynamically using `schema_editor.create_model()` tables are created in the database

Now the essence of the error. When trying to add a new entry through the admin site, an error occurs in the cache:
Can't pickle <class '_my_app_name.my_module.my_model_'>: attribute lookup _my_model_ on _my_app_name.my_module_ failed

Error tracing:
  File "D:\Envs\django\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Envs\django\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Envs\django\lib\site-packages\django\contrib\admin\options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\Envs\django\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Envs\django\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Envs\django\lib\site-packages\django\contrib\admin\sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "D:\Envs\django\lib\site-packages\django\contrib\admin\options.py", line 1655, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "D:\Envs\django\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Envs\django\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Envs\django\lib\site-packages\django\contrib\admin\options.py", line 1538, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\Envs\django\lib\site-packages\django\contrib\admin\options.py", line 1584, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "D:\Envs\django\lib\site-packages\django\contrib\admin\options.py", line 1097, in save_model
    obj.save()
  File "D:\Envs\django\lib\site-packages\django\db\models\base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "D:\Envs\django\lib\site-packages\django\db\models\base.py", line 774, in save_base
    post_save.send(
  File "D:\Envs\django\lib\site-packages\django\dispatch\dispatcher.py", line 180, in send
    return [
  File "D:\Envs\django\lib\site-packages\django\dispatch\dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  **File "D:\Envs\django\lib\site-packages\treenode\signals.py", line 36, in post_save_treenode
    sender.update_tree()
  File "D:\Envs\django\lib\site-packages\treenode\models.py", line 382, in update_tree
    update_cache(cls)
  File "D:\Envs\django\lib\site-packages\treenode\cache.py", line 61, in update_cache
    _set_cached_collections(l, d)
  File "D:\Envs\django\lib\site-packages\treenode\cache.py", line 33, in _set_cached_collections
    c.set('treenode_list', l)**
  File "D:\Envs\django\lib\site-packages\django\core\cache\backends\locmem.py", line 56, in set
    pickled = pickle.dumps(value, self.pickle_protocol)

I understand that dynamic use of the model was not provided for by you, as well as by the developers of Django. But I am weak in dealing with the cache. Perhaps I missed something when creating the model, registering it. I'm asking for ideas on what could have gone wrong. Models created in this way from standard prototypes work great.

I would appreciate any ideas

**Comment by TimurKhan** [comment]
Yes, of course. 
Sorry, this is a rather lengthy piece of code.
I have collected all related code in one place (for illustration). I quote it:

```
import uuid
from django.apps import apps
from django.conf import settings
from django.contrib import admin
from django.core.serializers import json
from django.db import models
from django.urls.base import clear_url_caches
from django.utils.module_loading import import_module
from importlib import reload
from flat_json_widget.widgets import FlatJsonWidget
from slugify import slugify  # python-slugify
from treenode.models import TreeNodeModel
from treenode.admin import TreeNodeModelAdmin
from treenode.forms import TreeNodeForm
from django import forms


class AbstractDirectory(TreeNodeModel):

    # Code
    code = models.SlugField(
        max_length=32,
        verbose_name='Code',
        help_text='Code value'
    )

    description = models.CharField(
        max_length=255,
        verbose_name='desctiption',
        help_text='Desctiption'
    )

    extra = models.JSONField(
        encoder=json.DjangoJSONEncoder,
        verbose_name='Additional fields',
        null=True,
        blank=True,
        help_text='Additional fields can be entered as value pairs'
    )

    class Meta: #(TreeNodeModel.Meta)
        """
        Meta class
        """
        abstract = True

    def __str__(self):
        arr = [self.code, self.description]
        return ': '.join(arr)


class AbstractDirectoryForm(TreeNodeForm):
    class Meta:
        fields = '__all__'
        widgets = {
            'extra': FlatJsonWidget,
            'description': forms.Textarea(attrs={'cols': 79, 'rows': 3}),
        }


class AbstractDirectoryAdmin(TreeNodeModelAdmin):
    form = AbstractDirectoryForm
    exclude = ('tn_priority',)


class DirectoryRegistry(TreeNodeModel):
    """
    Registry of user-created directories
    """

    treenode_display_field = 'name'

    is_section = models.BooleanField(
        default=True,
        choices=(
            (True, 'Create a new Registry Section'),
            (False, 'Create a new User Directory'),
        ),
        verbose_name='Action',
        help_text='Creating a new section will not create a new user \
directory. This option is intended for the convenience of organizing \
register elements.'
    )

    # Directory name
    title = models.CharField(
        max_length=16,
        unique=True,
        verbose_name='Name or title',
        help_text='Title for the short name of the directory'
    )

    name = models.CharField(
        max_length=255,
        unique=True,
        verbose_name='Name or title',
        help_text='User directory name'
    )

    description = models.CharField(
        max_length=255,
        verbose_name='Desctiption',
        help_text='Directory description'
    )

    # UUID
    uuid = models.UUIDField(
        default=uuid.uuid4,
        editable=False,
        verbose_name='Universally unique identifier (UUID)',
    )

    class Meta:
        """
        Mets class
        """
        ordering = ['name']
        verbose_name = 'Directpty'
        verbose_name_plural = 'User-created directories'

    def __str__(self):
        return self.name

    @property
    def app_label(self):
        return self._meta.app_label

    @property
    def model_name(self):
        return slugify(self.title, separator='_')

    @property
    def model(self):
        try:
            # model = globals()[self.model_name]
            return apps.get_model(self.app_label, self.model_name)
        except:
            return self.get_model()

    @classmethod
    def init(cls):
        """
        Init dynamic models after reloading
        """
        factory_models = cls.objects.all()
        for instance in factory_models:
            instance.get_model()
            instance.get_admin_model()

    def get_model(self):
        # Creat fields dictionary
        attrs = [('__module__', self.__class__.__module__,)]
        # Create model
        model = type(self.model_name, (AbstractDirectory,), dict(attrs))
        # Meta class correcting
        meta = getattr(model, '_meta', None)
        setattr(meta, 'app_label', self.app_label)
        setattr(meta, 'verbose_name', 'UCD: ' + self.title)
        setattr(meta, 'verbose_name_plural', 'UCD: ' + self.title)
        setattr(meta, 'default_permissions',
                ('add', 'change', 'delete', 'view',)
                )
        print(' - {0} model in module {1} is \
loaded'.format(self.model_name, self.app_label))
        return model

    def get_admin_model(self):
        attrs = {'model': self.model, 'extra': 1, }
        # Create model
        admin_model = type(self.name, (AbstractDirectoryAdmin,), dict(attrs))
        if not admin.site.is_registered(self.model):
            admin.site.register(self.model, admin_model)
            reload(import_module(settings.ROOT_URLCONF))
            clear_url_caches()
```

Signals.
Signals are used to eliminate developer fakap. With cascading delete actions in admin, they do not call the delete() method of the object. And the signal to create is just convenient.
```

def register_model(instance, make_admin = True):
        # Make admin model
    instance.get_model()
    if make_admin:
        instance.get_admin_model()

    # Make migrations
    with connection.schema_editor() as schema_editor:
        schema_editor.create_model(instance.model)
    # Create ContemtType
    opts = instance.model._meta
    ctype, created = ContentType.objects.get_or_create(
        app_label=opts.app_label,
        model=opts.object_name.lower())

    for code_tupel in _get_all_permissions(opts):
        codename = code_tupel[0]
        name = code_tupel[1]
        p, created = Permission.objects.get_or_create(
            codename=codename,
            content_type=ctype,
            defaults={'name': name})


def unregister_model(app_label, model):
    # Unregistry model
    try:
        del apps.all_models[app_label][model.__class__.__name__]
    except:
        pass
    # Kill admin model
    if admin.site.is_registered(model):
        admin.site.unregister(model)
    reload(import_module(settings.ROOT_URLCONF))
    clear_url_caches()
    # Kill tables
    try:
        with connection.schema_editor() as schema_editor:
            schema_editor.delete_model(model)
    except:
        print('DATACORE - Model deletion error')

    # Permission and ContentType cleaning
    try:
        content = ContentType.objects.get(
            app_label=app_label,
            model=model._meta.model_name
        )
        Permission.objects.filter(content_type=content).delete()
        content.delete()
        ContentType.objects.clear_cache()
    except:
        print('DATACORE - Error deleting ContentType and Permission \
objects')

    #gc.collect()
    # Clear apps cache
    apps.clear_cache()

@receiver(signals.post_save, sender = DirectoryRegistry)
def on_directory_save(sender, instance, created, **kwargs):
    if not created:
        return
    else:
        register_model(instance)

@receiver(signals.pre_delete, sender = DirectoryRegistry)
def on_directory_delete(sender, instance, **kwargs):
    unregister_model(instance.app_label, instance.model)
```

**Comment by fabiocaccamo** [comment]
@TimurKhan thank you for providing the code, that's a lot more than expected... could you submit a PR with a failing test case that should be succeed?

**Comment by TimurKhan** [comment]
I think this is impossible. Because a good example is as follows.
1. I have provided the code that dynamically creates the model. This model is not in the code, it is created on demand and user configuration. All that is known in advance is that it is a tree model.
2. When such a model is created, then in the administrator we can see it. It also exists in the database. All fields are created. Everything seems to be OK.
3. But when you try to insert any data into  this model, an error is caused, the log of which I gave. This error appears to be due to the fact that something needs to be done in order for it to appear in the cache. But what, alas, I do not know.

**Comment by fabiocaccamo** [comment]
- Have you checked [this](https://docs.python.org/3/library/pickle.html#what-can-be-pickled-and-unpickled)? Maybe your model contains something that can't be picked.
- Have you tried using another cache instead of locmem?

You should replay the scenario adding one piece at time to isolate the problem.

**Comment by TimurKhan** [comment]
Model in front of your eyes (AbstractDirectory). This is a standard abstract class, with standard fields. Factory (DirectoryRegistry) only reproduces this class by inheritance, making it real.
If this were the case, then inheritance from the standard model would also lead to a PicklingError. But this is not the case.

I have not tried changing the cache. I will try

**Comment by TimurKhan** [comment]
You can close this question. I didn't find the reason, but I did find a solution. You cannot make Treenode an abstract class and then generate a model. But you can generate a model from two classes at once, one of which is Treenode. Then everything works

**Comment by fabiocaccamo** [comment]
Thank you very much for this informations, it seems that the problem is related to how python manages abstract classes and inheritance... 

I'm sure that this could be helpful for someone else.

**Comment by TimurKhan** [comment]
Thank you!!!
