### ISSUE TITLE
If an object has no parent, admin will throw an exception

### ISSUE THREAD

**Issue by douglance** [fabiocaccamo/django-treenode#3]
I made a super simple, new Django app, and only added this package to test the admin.

```
Exception Type: AttributeError at /admin/tree/category/
Exception Value: 'Category' object has no attribute 'tn_parents_count'

```

**Comment by fabiocaccamo** [comment]
Have you installed the `0.6.4` version?

**Comment by douglance** [comment]
![It worked.](https://user-images.githubusercontent.com/4741454/39819178-d0b4875e-5370-11e8-96b2-824faf57a5cc.png)

Thanks for your help. Didn't realize the minor version had ticked up there.

Might be a good idea to include a screenshot showing the admin interface.

**Comment by fabiocaccamo** [comment]
I fixed some bugs caused by code refactoring just few hours ago.
Yes, I will add a screenshot of the admin interface, do you like it?
Any suggestion to improve the lib would be appreciated...

**Comment by douglance** [comment]
I see. Awesome. This is a fantastic start to the library. I'm looking forward to digging in and learning more.

I would like to see a tree-based editing interface in the detail view. So if I were editing a Category in the standard example, then I could see all the related nodes as collapsible, in-line forms. Adding drag-and-drop reordering would be incredible too.

**Comment by fabiocaccamo** [comment]
Thanks, I added inlines support to the todo list.

**Comment by fabiocaccamo** [comment]
Also added screenshots to README
