### ISSUE TITLE
QUESTION: Tree of different models

### ISSUE THREAD

**Issue by JuliusJacobitz** [fabiocaccamo/django-treenode#32]
Hi, 
I'm currently building an application and I want to manage a tree of different models in the django admin console.  Like the following:

```
├── Chapter1
└── Chapter2
    ├── Part1
    ├── Part2
``` 

Is this possilbe or is there a better way to achive this in django admin ? :)

**Comment by fabiocaccamo** [comment]
@JuliusJacobitz what do you mean by "manage"? What would you like to do precisely?

**Comment by JuliusJacobitz** [comment]
Basically a small cms to create update read and delete chapters, books and parts. New content should only be created through the django admin page.

**Comment by fabiocaccamo** [comment]
Actually the library supports multiple hierarchies made of instances of the same model.

This could be an interesting improvement, you could try to make your models proxy the `TreeNodeModel` and er give some feedback (I never did it before, I don't know what could happen).

**Comment by fabiocaccamo** [comment]
@JuliusJacobitz why you closed it? Have you tried to proxy the `TreeNodeModel`?

**Comment by JuliusJacobitz** [comment]
Hi @fabiocaccamo, no I unfortunately didn't try it out. There was no relevance anymore. Should I reopen for future questions?

**Comment by fabiocaccamo** [comment]
If you have the possibility to try the proxy model please give me some feedback. Let's keep it closed and re-open it in the future if needed.
