### ISSUE TITLE
remove verbose logging in django console

### ISSUE THREAD

**Issue by zszep** [fabiocaccamo/django-treenode#36]
it would be nice if the verbose logging in the django console could be removed, i.e. I get the following output for each added item:
```
[treenode] update acme.models.organization tree: executed 0 queries in 0.4567100000s.
 .
 .
 .
[treenode] update acme.models.organization tree: executed 0 queries in 0.589100000s.
```

**Comment by fabiocaccamo** [comment]
Actually there is logging only if `settings.DEBUG = True`, btw you're right.

**Comment by zszep** [comment]
Thks for the info. It would be nice to be able to disable logging in DEBUG mode. When developing the app, I have to recreate an organizational scheme with hundreds of items which clutters my console and other important information gets lost.
