### ISSUE TITLE
Any example for rendering django-treenode in django forms?

### ISSUE THREAD

**Issue by zszep** [fabiocaccamo/django-treenode#37]
Examples would be appreciated.

<a href="https://dashboard.polar.sh/fabiocaccamo/django-treenode/issues/37">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://dashboard.polar.sh/api/github/fabiocaccamo/django-treenode/issues/37/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://dashboard.polar.sh/api/github/fabiocaccamo/django-treenode/issues/37/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@zszep frankly I never used it in django forms, I have not any example to share / add to the documentation.

**Comment by TimurKady** [comment]
Our team has made a simple widget [treenode-widget](https://github.com/TimurKady/treenode-widget) that greatly improves usability for projects with large trees. Enjoy!

**Comment by fabiocaccamo** [comment]
@TimurKady is it possible to see a demo of it somewhere?

**Comment by TimurKady** [comment]
I will try to generate a small demo project

**Comment by Nathan-Cohen** [comment]
Here's an example of the html template I made to display parent and child nodes.
parent_file.html : 
```
<body>
    <ul>
    {% for node in childs %}
        {% if node in roots %}
            <li>
                {{ node.name }}
                {% if node.tn_children.all %}
                    <ul>
                        {% include 'node_child.html' with node=node %}
                    </ul>
                {% endif %}
            </li>
        {% endif %}
    {% endfor %}
    </ul>
</body>

```

node_child.html : 
```
{% for child in node.tn_children.all %}
    {% for id in childs %}
        {% if child == id %}
            <li>{{ child }}</li>
            {% if child.tn_children.all %}
                <ul>
                    {% include 'node_child.html' with node=child %}
                </ul>
            {% endif %}
        {% endif %}
    {% endfor %}
{% endfor %}
```

And here is the corresponding view : 
```
def show_tree(request):
    roots = Tree.objects.filter(tn_parent=None)
    childs = [node for node in Tree.objects.all()]

    context = {
        'roots': roots,
        'childs': childs
    }

    return render(request, 'tree.html', context)
```

**Comment by fabiocaccamo** [comment]
Thank you @Nathan-Cohen !
