### ISSUE TITLE
How to use methods like `set_parent` during manual RunPython in migrations?

### ISSUE THREAD

**Issue by jvacek** [fabiocaccamo/django-treenode#42]
**Python version**
3.9.1

**Django version**
2.2.24

**Package version**
0.17.0

**Current behaviour (bug description)**
My model was previously using the MPTT library, and so I'd like to transfer to TreeNode. However I am not really able to do the migration due to the methods not being available when using the `apps.get_model` tactic, and I think directly working on the keys might not be a good idea seeing as `set_parent` has things going on.

```py
def migrate_mptt_treenode(apps, schema_editor):
    MyModel = apps.get_model("myapp", "MyModel")
    for c in MyModel.objects.all():
        if c.parent is not None:
            c.set_parent(c.parent)
            c.save()
```
The info about the parent was stored in `parent` before, which is a TreeForeignKey Field from MPTT. I want to first migrate in the new fields from treenode, make the migration, and then remove the inheritance for the MPTTModel after the data is moved.

**Expected behaviour**
I know that `apps.get_model` doesn't make the methods available, so it's not that this _should_ work. Some alternatives for this use-case would be helpful though.

**Comment by fabiocaccamo** [comment]
@jvacek any update?

**Comment by jvacek** [comment]
We've ended up using the block below, which is quite sub-optimal given that we need to import the model to get access to the functions.

```py
def migrate_mptt_treenode(apps, schema_editor):
    MyModel = apps.get_model("app", "MyModel")
    models = MyModel.objects.all()
    if models:
        for m in models:
            if m.parent is not None:
                m.tn_parent_id = m.parent.id
                m.save()

        from project.app.models import MyModel as MyModelButImported

        if hasattr(MyModelButImported, "update_tree") and callable(MyModelButImported.update_tree()):
            MyModelButImported.update_tree()

```

It would be nice if there was a cleaner way to access the functions during migrations.

**Comment by fabiocaccamo** [comment]
@jvacek `update_tree` is a [class method](https://github.com/fabiocaccamo/django-treenode/blob/master/treenode/models.py#L388), even moving it to an external function you would have to pass the model class of the tree you want to update as argument, so I don't think that this problem would be solved.

Have you any suggestion?

**Comment by fabiocaccamo** [comment]
@jvacek any feedback?
