### ISSUE TITLE
tn_descendants_count is too small for big trees

### ISSUE THREAD

**Issue by jvies** [fabiocaccamo/django-treenode#51]
**Python version**
3.9

**Django version**
3.2

**Package version**
0.18.0

**Current behavior (bug description)**
since the fix of #44, a new exception is raised during my big tree building.

**Expected behavior**
use treenode for my ~ 100k nodes tree.

**Comment by fabiocaccamo** [comment]
@jvies you can upgrade to `0.18.1` version.
