### ISSUE TITLE
question: migrating from django-mptt to django-treenode

### ISSUE THREAD

**Issue by laith43d** [fabiocaccamo/django-treenode#55]
I used some of your work in my projects, and they are fantastic; thank you for your hard work.

I have a question, but I'm hesitant to explore till I know whether there is a history example; I searched and couldn't discover anything informative.

I'm working on a project where I'm using django-mptt, and it's becoming clear that it has constraints that are harming the overall development quality and experience. Is it your understanding that transitioning from mptt to treenode is possible/feasible?

Thank you, Layth.

**Comment by fabiocaccamo** [comment]
@laith43d thank you very much, I am very pleased that you use my libraries!
Surely the transition is possible, but I never did it.

**Comment by fabiocaccamo** [comment]
Maybe adding a command for doing the transition from other top libraries (such as `django-mptt`) would be great.

**Comment by fabiocaccamo** [comment]
@laith43d have you sketched any solution for doing this that could be useful as starting point for implementing this feature?

**Comment by laith43d** [comment]
hi there @fabiocaccamo, Well, I did some tests, but not for crucial production. But, the tests were sufficient for me to infer that the migration is dangerous, so we chose to undertake a full migration for the next release, which will necessitate additional testing.

Treenode has proven to be far superior to anything else, thus we decided to remain with it for future projects; thank you for your outstanding work.

In terms of the test bed, we simply added Treeenode, which included all tn_* fields, then ran a script to grab all relations from mptt and update accordingly, then reimplemented all methods that required tree capability, and after optimization, we were able to cut queries by approximately 70%. Afterwards we left mptt to ensure that nothing was broken.

Thus, we are positive that adding Treenode doesn't conflict with mptt, but not sure whether eliminating mptt altogether would bring errors or not. Although some methods conflicts, which was eliminated by implementing them locally to override the conflict.

**Comment by fabiocaccamo** [comment]
@laith43d thank you for the great feedback, it could be useful to someone else in the future.

If anyone would interested in submitting a well tested PR with a migration command (from `mptt` to `treenode`) it would be appreciated.

In the meantime, since it's not my intention to add a migration command myself I close this issue.
