### ISSUE TITLE
[Question] Can I use this library to represent related models?

### ISSUE THREAD

**Issue by simkimsia** [fabiocaccamo/django-treenode#7]
I have the following models:

- Structure
- StructureSeries
- StructureSeriesSlot

The model Structure has many StructureSeries. In turn, StructureSeries has many StructureSeriesSlot.

I noticed your example covers only for the records within the same model class to be treenodes within that model class.

Does it work for related models (related via ForeignKey Field)?

**Comment by fabiocaccamo** [comment]
@simkimsia, you can have multiple different trees at the same time, but in each tree nodes must be all of the same class (which must extend `TreeNodeModel` abstract class).

I hope to have answered correctly to your question.

**Comment by simkimsia** [comment]
Yes, you have answered. Thanks for answering.

Follow up question: What if I use GenericRelation via contenttypes framework? Would that work?

**Comment by fabiocaccamo** [comment]
The problem would be the same.
