### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by lambdamusic** [fabiocaccamo/django-treenode#8]
Been trying to create a few thousand items without any hierarchy infos, like this:

```

# models.py

class Customer(TreeNodeModel):

    treenode_display_field = 'name'
    name = models.CharField(max_length=50)

    class Meta(TreeNodeModel.Meta):
        verbose_name = 'Customer'
        verbose_name_plural = 'Customer'

# script.py

for x in names:
    obj, created = Customer.objects.get_or_create(name=x)
```

But the DB becomes incredibly slow after a couple hundred rows eg

```
[treenode] update bpids.models.Customer tree: executed 0 queries in 1.9379002410000226s.
[treenode] update bpids.models.Customer tree: executed 0 queries in 1.9850395860000276s.
[treenode] update bpids.models.Customer tree: executed 0 queries in 2.2034165819999885s.
[treenode] update bpids.models.Customer tree: executed 0 queries in 2.5427609600000096s.
[treenode] update bpids.models.Customer tree: executed 0 queries in 2.6210373019999906s.
[treenode] update bpids.models.Customer tree: executed 0 queries in 3.163530485000024s.
[treenode] update bpids.models.Customer tree: executed 0 queries in 1.538068753999994s.
```

So totally unusable... 

Anything I'm doing wrong?

**Comment by fabiocaccamo** [comment]
@lambdamusic every time a new node is created/deleted all siblings and descendants references are updated at db level, this is the cause of the slowdown.

I imagine that in your scenario read operations are not affected by any slowdown.

Personally I used it in a project with about 500 nodes (not all at the same level) without any problem.

Performance have been not the main focus, they could be improved a lot.
In this case I think that the siblings logic could be improved easily.

I appreciate your support and any suggestion will be appreciated.

**Comment by fabiocaccamo** [comment]
@lambdamusic I just released a `0.12.0` version with great performance improvements.

When you need to do bulk operations you should disable signals and trigger the tree update manually:

```python
from treenode.signals import no_signals

# ...
with no_signals():
	for x in names:
    	obj, created = Customer.objects.get_or_create(name=x)

Customer.update_tree()
```

**Comment by lambdamusic** [comment]
Thanks @fabiocaccamo - in the meantime I had to move to django-mptt but your API is simpler to use so I'll give it a try asap

**Comment by fabiocaccamo** [comment]
@lambdamusic ok, let me know!

**Comment by fabiocaccamo** [comment]
@lambdamusic any update?
