### ISSUE TITLE
String PK support

### ISSUE THREAD

**Issue by MourguesBenjamin** [fabiocaccamo/django-treenode#81]
Hello,

Currently, trying to compare string primary keys will fail because treenode will try to compare the pk (a string) to a number.

![image](https://user-images.githubusercontent.com/125553074/220586676-f83317ab-3817-4b18-8db7-15b087a63d7c.png)

Could we please add a support to string primary keys ? :) 

Thank you very much !

**Comment by fabiocaccamo** [comment]
@MourguesBenjamin nice catch, thank you for reporting this!

**Comment by fabiocaccamo** [comment]
@MourguesBenjamin feature available in `0.20.0` version.
