### ISSUE TITLE
Is it possible to use postgres `LTree` for tree implementation

### ISSUE THREAD

**Issue by baseplate-admin** [fabiocaccamo/django-treenode#91]
Hi,

So it seems that postgres has a [native tree implementation](https://www.postgresql.org/docs/current/ltree.html). Is it possible to add that functionality to the core?

<a href="https://dashboard.polar.sh/fabiocaccamo/django-treenode/issues/91">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://dashboard.polar.sh/api/github/fabiocaccamo/django-treenode/issues/91/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://dashboard.polar.sh/api/github/fabiocaccamo/django-treenode/issues/91/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@baseplate-admin frankly I don't know, if you want to work on a plugin for optionally taking advantage of it, feel free to submit a PR including tests.

**Comment by fabiocaccamo** [comment]
@baseplate-admin I will be glad to re-open this issue in the future if there will be a PR.
